overrides:
  - files:
      - "*.js"
      - "*.jsx"
      - "*.ts"
      - "*.tsx"
    options:
      singleQuote: true
  - files:
      - "*.less"
    options:
      singleQuote: true
  - files:
      - "*.md"
    options:
      proseWrap: "always"
  - files:
      - "*.xml"
    options:
      printWidth: 120
