[[language]]
name = "php"
file-types = ["php", "phtml"]
auto-format = true

[[language]]
name = "xml"
formatter = { command = "prettier", args = ["--parser", "xml", "--stdin-filepath", "source.xml", "--xml-whitespace-sensitivity", "ignore"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript", "--stdin-filepath", "source.js"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--parser", "typescript", "--stdin-filepath", "source.jsx"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript", "--stdin-filepath", "source.ts"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript", "--stdin-filepath", "source.tsx"] }
auto-format = true

[[language]]
name = "less"
scope = "source.less"
injection-regex = "less"
file-types = ["less"]
roots = []
formatter = { command = "prettier", args = ["--parser", "less", "--stdin-filepath", "source.less"] }
auto-format = true
indent = { tab-width = 4, unit = "    " }
grammar = "css"
